DrinkIt.WebApp/Models/Pedido.cs
using System;
using System.Collections.Generic;

namespace DrinkIt.WebApp.Models
{
    public class Pedido : EntidadeDominio
    {
        public List<Bebida> Bebidas { get; set; }
        public CartaoCredito Cartao1 { get; set; }
        public CartaoCredito Cartao2 { get; set; }
        public Cliente Cliente { get; set; }
        public Endereco EnderecoEntrega { get; set; }
        public DateTime DataCadastro { get; set; }
        public List<Status> Status { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal Desconto { get; set; }
        public decimal Frete { get; set; }

        public int IdEnderecoEntrega { get; set; }
        public int IdCartao1 { get; set; }
        public decimal ValorCartao1 { get; set; }
        public int IdCartao2 { get; set; }
        public decimal ValorCartao2 { get; set; }
        public int IdCupom { get; set; }
        public int IdCliente { get; set; }

        public bool Pagar2Cartoes { get; set; }

        public Cupom Cupom { get; set; }

        public Endereco NovoEndereco { get; set; }
        public CartaoCredito NovoCartao { get; set; }
    }
}

DrinkIt.WebApp/Controllers/PedidosController.cs
using DrinkIt.WebApp.Dao;
using DrinkIt.WebApp.Facade;
using DrinkIt.WebApp.Models;
using DrinkIt.WebApp.PurchaseApprove;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web.Mvc;

namespace DrinkIt.WebApp.Controllers
{
    public class PedidosController : Controller
    {
        // GET: Pedidos
        public ActionResult PvPedido()
        {
            int idCliente = ((Usuario)Session["Usuario"])?.Id ?? 0;

            List<Pedido> pedidos = new List<Pedido>();

            if (idCliente == 0)
            {
                pedidos = new PedidoDao().ConsultarTodos();
            }
            else
            {
                pedidos = new PedidoDao().ConsultarPorCliente(idCliente);
                ViewBag.RankingCliente = new ClienteDao().GetRankingCliente(idCliente);
            }

            pedidos.Reverse();

            return PartialView(pedidos);
        }

        public ActionResult PedidosAprovarSaida()
        {
            List<Pedido> pedidos = new PedidoDao().ConsultarTodos()
                .Where(x => x.Status.OrderByDescending(y => y.Id).First().Id == 2)
                .ToList();

            return PartialView(pedidos);
        }

        public ActionResult Checkout()
        {
            Usuario usuario = (Usuario)Session["Usuario"];
            if (usuario == null)
            {
                return RedirectToAction("Login", "Usuarios");
            }

            var listaEnderecos = new EnderecoDao().ConsultarPorCliente(usuario.Id);
            var listaCartoes = new CartaoDao().ConsultarPorCliente(usuario.Id);

            List<SelectListItem> ddlEnderecos = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Selecione um endereço",
                    Value = "0"
                }
            };
            List<SelectListItem> ddlCartoes = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Selecione um cartão",
                    Value = "0"
                }
            };

            listaEnderecos.ForEach(x => ddlEnderecos.Add(new SelectListItem
            {
                Text = string.Concat(x.Descricao, " - ", x.Logradouro, ", ", x.Numero, " ", x.Complemento),
                Value = x.Id.ToString(),
                Selected = x.Entrega
            }));
            listaCartoes.ForEach(x => ddlCartoes.Add(new SelectListItem
            {
                Text = string.Concat(x.Bandeira, " - final ", x.Numero.Substring(x.Numero.Length - 4)),
                Value = x.Id.ToString(),
                Selected = x.Preferencial
            }));

            ViewBag.Enderecos = ddlEnderecos;
            ViewBag.Cartoes = ddlCartoes;

            Cliente cliente = new Cliente
            {
                Carrinho = usuario?.Carrinho ?? new Carrinho()
            };

            Pedido pedido = new Pedido
            {
                Cliente = cliente,
                Bebidas = ((Usuario)Session["Usuario"])?.Carrinho?.Bebidas ?? new List<Bebida>()
            };

            //verifica se os itens ainda existem no estoque
            bool BebidasOK = new EstoqueDao().VerificaItensDisponiveis(pedido.Bebidas);

            if (!BebidasOK)
            {
                //retorna para o carrinho informando que o estoque foi atualizado
                return RedirectToAction("Index", "Carrinho", new { i = 1 });
            }

            return View(pedido);
        }

        [HttpPost]
        public ActionResult AtualizarQuantidadeBebida(int idBebida, int quantidade)
        {
            Usuario usuario = ((Usuario)Session["Usuario"]);

            foreach (var item in usuario.Carrinho.Bebidas)
            {
                if (item.Id == idBebida)
                {
                    item.Quantidade = quantidade;
                }
            }

            Session["Usuario"] = usuario;

            return RedirectToAction("Checkout");
        }

        public ActionResult FinalizarPedido(Pedido pedido)//idcartao1 e idenderecoentrega
        {
            Usuario usuario = (Usuario)Session["Usuario"] ?? new Usuario();
            try
            {
                
                pedido.IdCliente = usuario?.Id ?? 0;
                pedido.Bebidas = usuario?.Carrinho.Bebidas ?? new List<Bebida>();

                new PedidoDao().Cadastrar(pedido);

                int pedidoId = new PedidoDao().ObterUltimoIdInserido();

                new ProcedimentoTrocaStatus().EmProcessamento(pedidoId);

                Bandeira bandeira = new CartaoDao().ConsultarPorId(pedido.IdCartao1).Bandeira;

                if (new ValidadorCompra(bandeira).ValidarCompra())
                {
                    new ProcedimentoTrocaStatus().Aprovada(pedidoId);
                }
                else
                {
                    new ProcedimentoTrocaStatus().Reprovada(pedidoId);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }

            

            usuario.Carrinho.Bebidas.Clear();

            Session["Usuario"] = usuario;

            return RedirectToAction("Index", "Clientes");
        }

        public ActionResult Details(int id)
        {
            return View(new PedidoDao().ConsultarPorId(id));
        }

        [HttpPost]
        public ActionResult CalcularFretePedido(string pedido)
        {
            Pedido novoPedido = JsonConvert.DeserializeObject<Pedido>(pedido);

            decimal total = 0;

            novoPedido.Bebidas.ForEach(x => total += SimularFrete(x));

            var resultado = new
            {
                frete = total
            };

            return Json(resultado);
        }
        
        [HttpPost]
        public decimal SimularFrete(Bebida bebida)
        {
            decimal frete = Convert.ToDecimal((new Random().NextDouble() * (double)(bebida.Valor / 3)).ToString("0.##"));

            return frete;
        }

        public ActionResult SimularFreteDetails(string bebidaFrete)
        {
            Bebida novaBebida = JsonConvert.DeserializeObject<Bebida>(bebidaFrete);

            return Json(SimularFrete(novaBebida), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ColocarEmTransito(int pedidoId)
        {
            Pedido pedido = new PedidoDao().ConsultarPorId(pedidoId);

            if (pedido != null && pedido?.Bebidas != null && pedido.Bebidas.Any())
            {
                new ProcedimentoTrocaStatus().EmTransito(pedidoId);

                foreach (var item in pedido.Bebidas)
                {
                    new EstoqueDao().Baixa(item.Id, item.Quantidade);
                }

                new ProcedimentoTrocaStatus().EmTransporte(pedidoId);
                new ProcedimentoTrocaStatus().Entregue(pedidoId);
                new ProcedimentoTrocaStatus().Finalizado(pedidoId);

                return RedirectToAction("Index", "Usuarios");
            }
            else
            {
                return View("Error", "Home");
            }
        }

        public ActionResult PvBebidasPedido(string bebidas)
        {
            List<Bebida> listaBebidas = JsonConvert.DeserializeObject<List<Bebida>>(bebidas);

            return PartialView(listaBebidas);
        }
    }
}

DrinkIt.WebApp/Views/Pedidos/Checkout.cshtml
@model DrinkIt.WebApp.Models.Pedido

@using Newtonsoft.Json;
@using DrinkIt.WebApp.Models;

@{
    ViewBag.Title = "Checkout";
    Usuario usuario = (Usuario)Session["Usuario"];
    int i = 0;
}

<h2>Checkout</h2>

<hr />

@Html.Hidden("pedido", JsonConvert.SerializeObject(Model))

<div id="divCheckout">
    @using (Html.BeginForm("FinalizarPedido", "Pedidos", FormMethod.Post, new { @id = "FormPedido" }))
    {
        <input type="hidden" name="Cliente.Id" value="@usuario.Id" />

        <div class="panel panel-default">
            <div class="container" style="padding-left:0;padding-right:30px">

                <!--Endereço-->
                <div class="col-lg-4 col-md-4">
                    <div class="form-horizontal">
                        <h4>Endereço</h4>

                        <hr />

                        @Html.DropDownListFor(x => x.IdEnderecoEntrega, (List<SelectListItem>)ViewBag.Enderecos, new { @class = "form-control", @id = "dropEndereco" })
                        <label style="color:red;display:none" id="msgEnderecoInvalido">Insira um endereço válido.</label>
                    </div>
                </div>

                <!-- Forma de pagamento -->
                <div class="col-lg-4 col-md-4">
                    <div class="form-horizontal">
                        <h4>Forma de Pagamento</h4>
                        <hr />

                        @Html.DropDownListFor(x => x.IdCartao1, (List<SelectListItem>)ViewBag.Cartoes, new { @class = "form-control", @id = "dropCartao1" })
                        <label style="color:red;display:none" id="msgCartaoInvalido">Insira um cartão válido.</label>

                        <div>
                            <label class="control-label">Valor no cartão: </label>
                            <input readonly class="form-control money pay" id="valorCartao1" name="valorCartao1" value="@Model.Bebidas.Sum(x => x.ValorVenda * x.Quantidade)" />
                        </div>

                        <hr />

                        <div class="form-group" id="divCheckCartao2">
                            <label class="control-label" style="margin-right:15px;">Pagar com 2 Cartões <span style="color:orange">(min. R$10/cartão)</span>: </label>
                            <input type="checkbox" id="Pagar2Cartoes" name="Pagar2Cartoes" />
                        </div>

                        <div id="divCartao2" style="display:none">
                            @Html.DropDownListFor(x => x.IdCartao2, (List<SelectListItem>)ViewBag.Cartoes, new { @class = "form-control", @id = "dropCartao2" })
                            <label style="color:red;display:none" id="msgCartaoInvalido2">Insira um cartão válido.</label>

                            <div>
                                <label class="control-label">Valor no cartão 2: </label>
                                <input class="form-control money pay" id="valorCartao2" name="valorCartao2" value="0" />
                            </div>
                        </div>

                    </div>
                </div>

                <!-- Revisão do pedido -->
                <div class="col-lg-4 col-md-4">
                    <div class="form-horizontal">
                        <h4>Revisão do pedido</h4>
                        <hr />

                        <div class="panel panel-default">
                            <div class="panel-heading">Resumo do pedido</div>
                            <div class="panel-body">
                                <dl>
                                    @foreach (var item in Model.Bebidas)
                                    {
                                        <dt>
                                            <input type="hidden" name="Bebidas[@i].Id" value="@item.Id" />
                                            <input type="hidden" name="Bebidas[@i].Valor" value="@item.ValorVenda" />

                                            <label>@string.Concat(item.Nome, " ", item.Volume, " ", item.ValorVenda.ToString("C"), " X", item.Quantidade)</label>
                                        </dt>

                                        <dd>
                                            @Html.DisplayFor(model => item.Descricao)
                                        </dd>

                                        i++;
                                    }
                                </dl>

                                <dl>
                                    <dt>
                                        Valor da compra:
                                    </dt>
                                    <dd>
                                        @Model.Bebidas.Sum(x => x.ValorVenda * x.Quantidade)
                                    </dd>
                                </dl>

                                <dl>
                                    <dt>
                                        <label class="control-label">Desconto: </label>
                                    </dt>
                                    <dd>
                                        <span id="spanDesconto"></span>
                                        @Html.HiddenFor(x => x.Desconto)
                                    </dd>
                                </dl>

                                <dl>
                                    <dt>
                                        <label class="control-label">Frete: </label>
                                    </dt>
                                    <dd>
                                        <span id="spanFrete"></span>
                                        @Html.HiddenFor(x => x.Frete)
                                    </dd>
                                </dl>

                            </div>
                            <div class="panel-footer">
                                <label class="control-label">Valor Total: </label>
                                <label class="control-label" style="float:right">
                                    <span id="spanValorTotal">@Model.Bebidas.Sum(x => x.ValorVenda * x.Quantidade).ToString("C")</span>
                                </label>
                                <input type="hidden" id="ValorTotal" name="ValorTotal" value="@Model.Bebidas.Sum(x => x.ValorVenda * x.Quantidade)" />
                                <input type="hidden" id="ValorTotalInicial" name="ValorTotalInicial" value="@Model.Bebidas.Sum(x => x.ValorVenda * x.Quantidade)" />
                            </div>
                        </div>
                        <div id="warnTroco" style="display:none">
                            <label style="color:orange">Será gerado um cupom de troco no valor de: <span id="spanVlrTroco"></span>.</label>
                        </div>
                    </div>
                    <br />

                    <div class="form-group">
                        <label class="control-label">Calcular frete:</label>
                        <div style="display: inline-flex;">
                            <input id="Cep" class="form-control" type="text" name="Cep" placeholder="00000-000" value="" maxlength="9" />
                            <button id="btnCalcularFrete" type="button" class="btn btn-default" style="float:right">Calcular</button>
                            <input type="hidden" id="hiddenValorFrete" value="0" />
                        </div>
                        <label style="color:forestgreen" class="control-label">
                            <span id="ResultadoValorFrete"></span>
                        </label>
                        <label style="color:red;display:none" id="msgCepInvalido">Insira um CEP válido para calcular o frete.</label>
                        <input type="hidden" id="hiddenValidarCep" value="0" />
                    </div>

                    <hr />

                    <div class="form-group">
                        <label for="inputCupomDesconto">Cupom:</label>
                        <input type="text" class="form-control" id="inputCupom" placeholder="Insira um cupom válido">
                        @Html.HiddenFor(x => x.IdCupom)
                        <input name="Cupom.Valor" type="hidden" id="hiddenValorCupom" value="0" />
                        <br />
                        <button id="btnValidarCupom" class="btn btn-info" type="button">Validar Cupom</button>
                        <span id="spanCupomValido" style="color:forestgreen;display:none;"><strong>Cupom válido!</strong></span>
                        <span id="spanCupomInvalido" style="color:darkred;display:none;"><strong>Cupom inválido!</strong></span>
                    </div>

                </div>
            </div>

            <hr />

            <div class="form-horizontal">
                <div class="form-group" align="right" style="margin-right:15px">
                    <button id="btnFinalizarPedido" class="btn btn-success" type="button">Finalizar Compra</button>
                </div>
            </div>
        </div>
    }
</div>

@*@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")*@

@section Scripts{


    <script src="~/Scripts/Pedidos/Script_Checkout_Pedidos.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.min.js"></script>

    <script>
        $('.money').mask('#.##0,00', { reverse: true });
        $('#Cep').mask('00000-000', { reverse: true });
    </script>

}

DrinkIt.WebApp/Views/Pedidos/Details.cshtml
@model DrinkIt.WebApp.Models.Pedido

@{
    ViewBag.Title = "Pedido - Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Id do Pedido
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnderecoEntrega)
        </dt>

        <dd>
            @string.Concat(Model.EnderecoEntrega.Descricao, " - ", Model.EnderecoEntrega.Logradouro, ", ", Model.EnderecoEntrega.Numero,
           " ", Model.EnderecoEntrega.Complemento, " ", Model.EnderecoEntrega.Bairro, " ", Model.EnderecoEntrega.Cidade, " ",
           Model.EnderecoEntrega.Estado, " ", Model.EnderecoEntrega.CEP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotal)
        </dt>

        <dd>
            @Model.ValorTotal.ToString("C")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desconto)
        </dt>

        <dd>
            @Model.Desconto.ToString("C")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Frete)
        </dt>

        <dd>
            @Model.Frete.ToString("C")
        </dd>

    </dl>

    <hr />

    <h4>Bebidas</h4>
    <dl class="dl-horizontal">
        @foreach (var item in Model.Bebidas)
        {
            <dt>
                @Html.DisplayNameFor(model => item.Nome)
            </dt>

            <dd>
                @string.Concat(item.Nome, " ", item.Descricao, " ", item.Marca, " ", item.Sabor, " ", item.Peso, " - X", item.Quantidade)
            </dd>
        }

        <dt></dt>
        <dd><hr /></dd>

        <dt>
            Valor da Compra
        </dt>
        <dd>
            @Model.Bebidas.Sum(x => x.Valor * x.Quantidade).ToString("C")
        </dd>
    </dl>

    <hr />

    <h4>Histórico de Status</h4>
    <table class="table table-bordered table-condensed table-hover table-responsive table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status.First().DataAtualizacao)
            </th>
        </tr>

        @foreach (var item in Model.Status.OrderByDescending(x => x.DataAtualizacao))
        {
            <tr>
                <td>
                    @string.Concat(item.Id,
                                    " - ",
                                    item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataAtualizacao)
                </td>
            </tr>
        }

    </table>
</div>
<p>
    @Html.ActionLink("Voltar", "Index", "Clientes")
</p>

DrinkIt.WebApp/Views/Pedidos/PedidosAprovarSaida.cshtml
@model IEnumerable<DrinkIt.WebApp.Models.Pedido>

@{ 
    Layout = null;
}

@if (Model.Count() == 0)
{
    <h4 style="padding-left:1%">Nenhum pedido encontrado.</h4>
}
else
{
    <table class="table table-bordered table-condensed table-hover table-responsive table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status.FirstOrDefault().DataAtualizacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorTotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status.OrderByDescending(x => x.DataAtualizacao).FirstOrDefault().DataAtualizacao)
                </td>
                <td>
                    @string.Concat(item.Status.OrderByDescending(x => x.DataAtualizacao).FirstOrDefault().Id,
                                    " - ",
                                    item.Status.OrderByDescending(x => x.DataAtualizacao).FirstOrDefault().Descricao)
                </td>
                <td align="center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle btnopcoesPedidos" data-toggle="dropdown" id="opcoesPedidos">
                            Opções <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                @using (Html.BeginForm("ColocarEmTransito", "Pedidos", FormMethod.Post))
                                {
                                    @Html.Hidden("pedidoId", item.Id)
                                    <button class="btn btn-primary btnColocarTransito" type="submit">Colocar em Trânsito</button>
                                }
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
        }

    </table>
}

DrinkIt.WebApp/Views/Pedidos/PvBebidasPedido.cshtml
@model IEnumerable<DrinkIt.WebApp.Models.Bebida>

<dl class="dl-horizontal">
        @if (Model.Count() != 0 && Model != null)
        {
            foreach (var item in Model)
            {
                <dt>
                    @item.Nome - @item.Volume
                </dt>

                <dd>
                    <div style="display:inline">
                        <input type="checkbox" class="checkboxTrocaItem" data-iditem="@item.Id"/>
                        <input value="0" type="number" disabled name="QtdeBebidas" data-iditem="@item.Id" style="width: 80px;display:inline" class="form-control QtdeTroca" onkeydown="return false" min="1" max="@item.Quantidade" />
                        <input type="hidden" disabled class="clHiddenIdBebida" data-iditem="@item.Id" value="@item.Id" name="IdBebidas" />
                    </div>
                </dd>
            }
        }

    </dl>
<label style="color:red;display:none" id="msgErrorBebidas">Selecione ao menos uma bebida para trocar!</label>

<script>

    $('.checkboxTrocaItem').change(function () {
        var iditem = $(this).attr('data-iditem');
        //[value='Hot Fuzz']
        if ($(this).prop('checked') == true) {
            $('.QtdeTroca[data-iditem="' + iditem + '"]').prop('disabled', false);
            $('.QtdeTroca[data-iditem="' + iditem + '"]').val(1);
            $('.clHiddenIdBebida[data-iditem="' + iditem + '"]').prop('disabled', false);
        } else {
            $('.QtdeTroca[data-iditem="' + iditem + '"]').prop('disabled', true);
            $('.QtdeTroca[data-iditem="' + iditem + '"]').val(0);
            $('.clHiddenIdBebida[data-iditem="' + iditem + '"]').prop('disabled', true);
        }
    });
</script>