DrinkIt.WebApp/Controllers/PrecificacaoController.cs
using DrinkIt.WebApp.Dao;
using DrinkIt.WebApp.Facade;
using DrinkIt.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkIt.WebApp.Controllers
{
    public class PrecificacaoController : Controller
    {
        private readonly IDao<GrupoPrecificacao> Dao;
        private readonly IFachada<GrupoPrecificacao> Fachada;

        public PrecificacaoController()
        {
            Dao = new PrecificacaoDao();
            Fachada = new Fachada<GrupoPrecificacao>(Dao);
        }

        // GET: Precificacao
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PvGrupoPrecificacao()
        {
            return PartialView(Fachada.ConsultarTodos()); 
        }

        // GET: Precificacao/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Precificacao/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Precificacao/Create
        [HttpPost]
        public ActionResult Create(GrupoPrecificacao precificacao)
        {
            try
            {
                // TODO: Add insert logic here

                Fachada.Cadastrar(precificacao);

                return RedirectToAction("Index", "Usuarios");
            }
            catch
            {
                return View();
            }
        }

        // GET: Precificacao/Edit/5
        public ActionResult Edit(int id)
        {
            return View(Fachada.ConsultarPorId(id));
        }

        // POST: Precificacao/Edit/5
        [HttpPost]
        public ActionResult Edit(GrupoPrecificacao grupo)
        {
            try
            {
                // TODO: Add update logic here
                Fachada.Alterar(grupo);
                return RedirectToAction("Index", "Usuarios");
            }
            catch
            {
                return View();
            }
        }

        // GET: Precificacao/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Precificacao/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DrinkIt.WebApp/Views/Precificacao/Create.cshtml
@model DrinkIt.WebApp.Models.GrupoPrecificacao

@{
    ViewBag.Title = "Create";
}

<h2>Novo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Grupo de Precificacao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Margem de Lucro(%)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MargemLucro, new { htmlAttributes = new { @class = "form-control", @id = "margemLucroCreate" } })
                @Html.ValidationMessageFor(model => model.MargemLucro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Usuarios", null, new { @class = "btn btn-default" })
</div>

@section Scripts{

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.min.js"></script>

    <script>
        $('#margemLucroCreate').mask('#.##0,00', { reverse: true });
    </script>

}

DrinkIt.WebApp/Views/Precificacao/Edit.cshtml
@model DrinkIt.WebApp.Models.GrupoPrecificacao

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Grupo de Precificacao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Margem de Lucro(%)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MargemLucro, new { htmlAttributes = new { @class = "form-control", @id = "margemLucroEdit" } })
                @Html.ValidationMessageFor(model => model.MargemLucro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Usuarios")
</div>

@section Scripts{

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.min.js"></script>

    <script>
        $('#margemLucroEdit').mask('#.##0,00', { reverse: true });
    </script>

}

DrinkIt.WebApp/Views/Precificacao/PvGrupoPrecificacao.cshtml
@model IEnumerable<DrinkIt.WebApp.Models.GrupoPrecificacao>

<p>
    @Html.ActionLink("Novo", "Create", "Precificacao", null, new { @class = "btn btn-success", @style = "margin-left:1%" } )
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Descrição")
        </th>
        <th>
            @Html.DisplayName("Margem de Lucro")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MargemLucro)
        </td>
        <td>
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Opções <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn-warning" })</li>                    
                </ul>
            </div>
        </td>
    </tr>
}

</table>