DrinkIt.WebApp/Models/Telefone.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DrinkIt.WebApp.Models
{
    public class Telefone : EntidadeDominio
    {
        public int IdCliente { get; set; }
        public int IdTipo { get; set; }
        public string DescricaoTipo { get; set; }
        public int DDD { get; set; }
        public string Numero { get; set; }
    }
}

DrinkIt.WebApp/Controllers/TelefonesController.cs
using DrinkIt.WebApp.Dao;
using DrinkIt.WebApp.Facade;
using DrinkIt.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkIt.WebApp.Controllers
{
    public class TelefonesController : Controller
    {
        private readonly IDao<Telefone> Dao;
        private readonly IFachada<Telefone> Fachada;
        private readonly ITelefone telefoneDao;

        public TelefonesController()
        {
            Dao = new TelefoneDao();
            Fachada = new Fachada<Telefone>(Dao);
            telefoneDao = new TelefoneDao();
        }

        // GET: Telefones
        public ActionResult Index()
        {
            return View();
        }

        // GET: Telefones/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Telefones/Create
        public ActionResult Create()
        {
            ViewBag.ErroTelefone = "";
            return View();
        }

        // POST: Telefones/Create
        [HttpPost]
        public ActionResult Create(Telefone telefone)
        {
            try
            {
                // TODO: Add insert logic here
                if(telefone.DDD == 0 || telefone.Numero == null)
                {
                    ViewBag.ErroTelefone = "Dados inválidos. Insira o DDD e o número corretamente.";
                    return View(telefone);
                }

                telefone.IdCliente = ((Usuario)Session["Usuario"])?.Id ?? 0;

                Resultado resultado = Fachada.Cadastrar(telefone);

                return RedirectToAction("Index", "Clientes");
            }
            catch(Exception ex)
            {
                return View();
            }
        }

        // GET: Telefones/Edit/5
        public ActionResult Edit(int id)
        {
            Telefone telefone = new Telefone();
            telefone = Fachada.ConsultarPorId(id);
            return View(telefone);
        }

        // POST: Telefones/Edit/5
        [HttpPost]
        public ActionResult Edit(Telefone telefone)
        {
            try
            {
                Fachada.Alterar(telefone);

                return RedirectToAction("Index", "Clientes");
            }
            catch
            {
                return View();
            }
        }
                
        // POST: Telefones/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                Fachada.Excluir(id);
                return RedirectToAction("Index", "Clientes");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult PvTelefone()
        {
            try
            {
                int idCliente = ((Usuario)Session["Usuario"]).Id;

                return PartialView(telefoneDao.ConsultarPorCliente(idCliente));
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
    }
}

DrinkIt.WebApp/Views/Telefones/Create.cshtml
@model DrinkIt.WebApp.Models.Telefone

@{
    ViewBag.Title = "Novo Telefone";
    string mensagemErro = ViewBag.ErroTelefone;
}

<h2>Novo Telefone</h2>

@using (Html.BeginForm("Create", "Telefones", FormMethod.Post, new { @id = "FormCreateTelefone" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tipo Telefone", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" name="IdTipo">
                    <option value="1">Residencial</option>
                    <option value="2">Celular</option>
                    <option value="3">Comercial</option>
                </select>
                @Html.ValidationMessageFor(model => model.IdTipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DDD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="DDD" class="form-control" id="dddTelefone" />
                <label class="control-label msgErro" style="color:red;display:none" id="msgErroDDD">Insira um DDD válido!</label>
                @Html.ValidationMessageFor(model => model.DDD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control", @id = "numeroTelefone" } })
                <label class="control-label msgErro" style="color:red;display:none" id="msgErroNumero">Insira um número válido!</label>
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label style="color:red">@mensagemErro</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Salvar" class="btn btn-default" id="btnSalvarCreateTel"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Clientes", null, new { @class = "btn btn-default" })
</div>


@*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@

@section Scripts{
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.min.js"></script>
    <script src="~/Scripts/Telefones/Script_Create_Telefone.js"></script>
    <script>
        $('#dddTelefone').mask('00', { reverse: true });
        $('#numeroTelefone').mask('00000-0000', { reverse: true });
    </script>

}

DrinkIt.WebApp/Views/Telefones/Edit.cshtml
@model DrinkIt.WebApp.Models.Telefone

@{
    ViewBag.Title = "Editar Telefone";
}

<h2>Editar</h2>

@using (Html.BeginForm("Edit", "Telefones", FormMethod.Post, new { @id = "FormEditTelefone" }) )
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Telefone</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Tipo Telefone", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" name="IdTipo">
                    <option value="1">Residencial</option>
                    <option value="2">Celular</option>
                    <option value="3">Comercial</option>
                </select>
                @Html.ValidationMessageFor(model => model.IdTipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DDD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DDD, new { htmlAttributes = new { @class = "form-control", @id = "dddTelefone", @type = "text" } })
                <label class="control-label msgErro" style="color:red;display:none" id="msgErroDDD">Insira um DDD válido!</label>
                @Html.ValidationMessageFor(model => model.DDD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control", @id = "numeroTelefone" } })
                <label class="control-label msgErro" style="color:red;display:none" id="msgErroNumero">Insira um número válido!</label>
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Salvar" class="btn btn-default" id="btnSalvarEditTel" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Clientes", null, new { @class = "btn btn-default" })
</div>

@section Scripts{
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.min.js"></script>

    <script src="~/Scripts/Telefones/Script_Edit_Telefone.js"></script>

    <script>
        $('#dddTelefone').mask('00', { reverse: true });
        $('#numeroTelefone').mask('00000-0000', { reverse: true });
    </script>

}

DrinkIt.WebApp/Views/Telefones/PvTelefone.cshtml
@model IEnumerable<DrinkIt.WebApp.Models.Telefone>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

@if (Model.Count() == 0)
{
    <h4 style="padding-left:1%">Nenhum telefone encontrado.</h4>
}
else
{

    <table class="table">
        <tr>
            <th>
                Tipo
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Numero)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DescricaoTipo)
                </td>
                <td>
                    (@Html.DisplayFor(modelItem => item.DDD))@Html.DisplayFor(modelItem => item.Numero)
                </td>
                <td align="center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Opções <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })</li>
                            <li><a class="btn btn-danger btnExcluirTelefone" data-id="@item.Id" data-numero="@item.Numero" data-ddd="@item.DDD" href="#" onclick="">Excluir</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        }

    </table>

}